### ISSUE TITLE
Small issue with comments

### ISSUE THREAD

**Issue by abhijit-15** [lathertonj/chunity-vscode#1]
Hi Jack,

Not sure if you have noticed this small issue. Take a look at *.RunCode(@"*

![image](https://user-images.githubusercontent.com/33440501/47323465-c05de580-d610-11e8-8354-3df0f40c4c28.png)

Multi-line comments are perfect! :)
![image](https://user-images.githubusercontent.com/33440501/47323704-c1dbdd80-d611-11e8-9cc3-249cbfa78e79.png)

Best,
Abhi

**Comment by lathertonj** [comment]
Thanks! I will work on a fix for this soon. It should be pretty simple.

**Comment by lathertonj** [comment]
Fixed in a88ae2b424e31fa994b2c3e8451688f46c763ff0 !

**Comment by abhijit-15** [comment]
You are the best! Thanks :)
